- name: Deploy DevOps Monitoring Platform
  hosts: remote
  vars_files:
    - vars.yml
  become: true

  tasks:
    - name: Create project directory
      file:
        path: /opt/devops-monitoring
        state: directory

    - name: Copy project files to remote
      synchronize:
        src: ../
        dest: /opt/devops-monitoring
        rsync_opts:
          - "--exclude=ansible"
          - "--exclude=.git"
          - "--exclude=terraform"
          - "--exclude=backup"

    - name: Run docker-compose up
      command: docker compose up -d
      args:
        chdir: /opt/devops-monitoring
